### ISSUE TITLE
Rotate Camera

### ISSUE THREAD

**Issue by jimthedj65** [aawobdev/pi-camera-timelapse#1]
Hi There,

Thanks for this great script, is there any way to rotate the camera. I am using an RPI4 and need to rotate the camera 90 deg to the right as it captures sideways.

Thanks for any assistance.

**Comment by aawobdev** [comment]
Hey! Apologies for the lateness. I'll try look into this at the weekend.  Let me know if you have any further info/suggestions

**Comment by aawobdev** [comment]
> Hi There,
> 
> Thanks for this great script, is there any way to rotate the camera. I am using an RPI4 and need to rotate the camera 90 deg to the right as it captures sideways.
> 
> Thanks for any assistance.

This has been included now as an additional OPTIONAL command line argument, you can use 0, 90, 180 or 270 or leave it out.
[Have a look](https://github.com/aawobdev/pi-camera-timelapse#rotation)
